spring:
  application:
    name: backend
  profiles:
    include: api

google:
  genai:
    model: "gemini-1.5-flash"

  # H2 데이터베이스 설정 (해커톤 꿀조합)
  datasource:
    url: jdbc:h2:mem:potatoesdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true # 브라우저에서 DB 확인 가능
      path: /h2-console

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update # 엔티티 수정 시 DB 테이블 자동 반영
    show-sql: true # 실행되는 SQL 로그 출력
    properties:
      hibernate:
        format_sql: true # SQL 예쁘게 출력